## OUTPUT_CONFIG:
OUTPUT_DIR: ./.compiler_output
DEBUG: False

## ALGORITHM_CONFIG:
# max length
MAX_LEN: 2048
# sparse param
FSB_BLOCK_SIZE: 16
MASK_LAYOUT_BLOCK_SIZE: 64

## FREQUENCY_CONFIG:
CLOCK_FREQ_MHZ: 225

## PARALLEL_CONFIG:
# SLR
SLR_NUM: 4
# mm parallelism
MM_PARALLEL_N: 2
MM_PARALLEL_K: 16
MM_PARALLEL_M: 128
# mv parallelism
MV_PARALLEL_N: 64
MV_PARALLEL_K: 16
MV_PARALLEL_M: 1
# compute start
MM_START_N_NUM: 16
MM_START_M_NUM: 128
MV_START_N_NUM: 512
MV_START_M_NUM: 1
# misc parallelism
SOFTMAX_PARALLEL_K: 16
LAYERNORM_PARALLEL_K: 16
ELTWISE_PARALLEL_K: 16
SILU_PARALLEL_K: 16

## BUFFER_CONFIG
# A buffer (multiple banks)
A_BUFFER_DEPTH: 4096
A_BUFFER_PER_BANK_WIDTH_B: 16 # MM_PARALLEL_K
A_BUFFER_MM_PER_CHANNEL_BANK_NUM: 16
A_BUFFER_MV_PER_CHANNEL_BANK_NUM: 4 # A_BUFFER_MM_PER_CHANNEL_BANK_NUM / 4
A_BUFFER_MM_PER_CHANNEL_WIDTH_B: 256 # A_BUFFER_PER_BANK_WIDTH_B * A_BUFFER_PER_CHANNEL_BANK_NUM = 16 * 8
A_BUFFER_MV_PER_CHANNEL_WIDTH_B: 64 # A_BUFFER_MM_PER_CHANNEL_WIDTH_B / 4
A_BUFFER_HBM_CHANNEL_NUM: 8
A_BUFFER_HBM_CHANNEL_START_ID: 0
# B buffer (only 1 bank)
B_BUFFER_DEPTH: 4096
B_BUFFER_MM_BANK_WIDTH_B: 32 # MM_PARALLEL_N * MM_PARALLEL_K
B_BUFFER_MV_BANK_WIDTH_B: 16 # B_BUFFER_BANK_WIDTH_B / 2
B_BUFFER_HBM_CHANNEL_NUM: 1
B_BUFFER_HBM_CHANNEL_ID: 8
# global buffer (multiple banks, same shape as A buffer)
GLOBAL_BUFFER_DEPTH: 512
GLOBAL_BUFFER_PER_BANK_WIDTH_B: 16
GLOBAL_BUFFER_MM_PER_CHANNEL_BANK_NUM: 16
GLOBAL_BUFFER_MM_PER_CHANNEL_WIDTH_B: 256
GLOBAL_BUFFER_MV_PER_CHANNEL_BANK_NUM: 2 # GLOBAL_BUFFER_MM_PER_CHANNEL_BANK_NUM / 8
GLOBAL_BUFFER_MV_PER_CHANNEL_WIDTH_B: 32 # GLOBAL_BUFFER_MM_PER_CHANNEL_WIDTH_B / 8
GLOBAL_BUFFER_MISC_PER_CHANNEL_BANK_NUM: 1
GLOBAL_BUFFER_MISC_PER_CHANNEL_WIDTH_B: 16
GLOBAL_BUFFER_HBM_CHANNEL_NUM: 8
GLOBAL_BUFFER_HBM_CHANNEL_START_ID: 0
# meta buffer (only 1 bank)
META_BUFFER_DEPTH: 4096 # B_BUFFER_DEPTH
META_BUFFER_BANK_WIDTH_B: 16 # half of B_BUFFER_BANK_WIDTH_B
META_BUFFER_HBM_CHANNEL_NUM: 1
META_BUFFER_HBM_CHANNEL_ID: 8
# FSB buffer (only 1 bank)
FSB_BUFFER_DEPTH: 4096
FSB_BUFFER_BANK_WIDTH_B: 1
FSB_BUFFER_HBM_CHANNEL_NUM: 1
FSB_BUFFER_HBM_CHANNEL_ID: 8
# bias buffer (only 1 bank)
BIAS_BUFFER_DEPTH: 4096
BIAS_BUFFER_BANK_WIDTH_B: 64
BIAS_BUFFER_HBM_CHANNEL_NUM: 1
BIAS_BUFFER_HBM_CHANNEL_ID: 8
# inst
INST_HBM_CHANNEL_NUM: 1
INST_HBM_CHANNEL_ID: 9

## HBM_CONFIG:
HBM_CHANNEL_SIZE_MB: 256
HBM_TOTAL_SIZE_GB: 8
HBM_CHANNEL_NUM: 32
HBM_BW_GB_PER_SEC: 819.2 # GB/s
HBM_BW_SAME_CHANNEL_EFFICIENCY: 0.7
HBM_BW_CROSS_CHANNEL_EFFICIENCY: 0.35